server:
  port: 8007



##数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_2020?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class: com.mysql.cj.jdbc.Driver
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 2d808414-8ca7-4526-8a83-bb266f55b5ad

#在服务调用方配置负载均衡策略
server-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


# mybatis配置信息
mybatis:
  # mapper xml文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 映射pojo所在的包
  type-aliases-package: shop.user.com.entity

#seata配置
seata:
  application-id: ${spring.application.name}
  #事务群组（可以每个运用独立取名，也可以使用相同的名字），要与服务端service.vgroup-mapping的后缀对应
  tx-service-group: default
  service:
    vgroup-mapping:
      default: default
    grouplist:
      default: 127.0.0.1:8091