
#数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_2020?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver

# mybatis配置信息
mybatis:
  # mapper xml文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 映射pojo所在的包
  type-aliases-package: com.common.entity
